# Generated by Django 4.2.16 on 2024-10-12 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseEventTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weekday", models.CharField(max_length=10)),
                ("start", models.IntegerField()),
                ("end", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="DeadlineEventModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_name", models.CharField(max_length=8)),
                ("session", models.CharField(max_length=7)),
                ("event_type", models.CharField(max_length=10)),
                ("deadline_date", models.DateField()),
                ("deadline_time", models.IntegerField(default=86340000)),
            ],
        ),
        migrations.CreateModel(
            name="UserStudySetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("semester_start", models.DateField()),
                ("semester_end", models.DateField()),
                ("preferred_study_start", models.IntegerField()),
                ("preferred_study_end", models.IntegerField()),
                ("study_level", models.CharField(max_length=10)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CourseEventModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_name", models.CharField(max_length=8)),
                ("session", models.CharField(max_length=7)),
                ("event_type", models.CharField(max_length=10)),
                (
                    "time",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ActivityPlanner.courseeventtime",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
